services:
  app-db:
    image: mysql:latest
    container_name: app-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: appDb
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - 3306
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ../db:/docker-entrypoint-initdb.d
      - appDb:/var/lib/mysql

  apache:
    container_name: apache
    build:
      context: ../
      dockerfile: docker/dockerfile
    environment:
      MYSQL_HOST: app-db
    ports:
      - ${APP_PORT}:80
    volumes:
      - ../src:/var/www/html/
      - ../apache/apache2.conf:/etc/apache2/apache2.conf
      - ../apache/sites-enabled/000-default.conf:/etc/apache2/sites-enabled/000-default.conf

volumes:
  appDb:
