FROM php:7.4-apache

# Install mysqli extension
RUN docker-php-ext-install mysqli

# Setup workdir
ENV WORKDIR /var/www/html
WORKDIR $WORKDIR

# Copy source to container
COPY src/ .
COPY /apache/apache2.conf /etc/apache2/apache2.conf
COPY /apache/sites-enabled/000-default.conf /etc/apache2/sites-enabled/000-default.conf

# Copy .env file to container
COPY src/.env .env

# Update package list dan install sudo
RUN apt-get update && \
    apt-get install -y sudo && \
    rm -rf /var/lib/apt/lists/*

RUN a2enmod rewrite

# Start Apache server
CMD ["apache2-foreground"]
