name: PHP Composer and Docker Compose

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker
      run: docker pull composer:latest

    - name: Validate composer.json and composer.lock
      run: |
        docker run --rm \
        -v ${{ github.workspace }}:/app \
        composer:latest validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: |
        docker run --rm \
        -v ${{ github.workspace }}:/app \
        composer:latest install --prefer-dist --no-progress

    # Run Docker Compose
    - name: Set up Docker Compose
      run: |
        docker-compose --version

    - name: Build and run services with Docker Compose
      run: |
        docker-compose -f docker/docker-compose.yml up -d --build

    - name: Run tests
      run: |
        docker-compose -f docker/docker-compose.yml exec <service_name> composer run-script test

    - name: Shut down services
      run: |
        docker-compose -f docker/docker-compose.yml down
