name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Create .env file
        run: |
          echo "APP_HOST=${{ secrets.APP_HOST }}" > src/.env
          echo "APP_PORT=${{ secrets.APP_PORT }}" >> src/.env
          echo "SENDER_EMAIL_ADDRESS=${{ secrets.SENDER_EMAIL_ADDRESS }}" >> src/.env
          echo "SENDER_EMAIL_PASSWORD=${{ secrets.SENDER_EMAIL_PASSWORD }}" >> src/.env
          echo "MYSQL_HOST=${{ secrets.MYSQL_HOST }}" >> src/.env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> src/.env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> src/.env
          echo "MYSQL_PORT=${{ secrets.MYSQL_PORT }}" >> src/.env
          echo "MYSQL_DB=${{ secrets.MYSQL_DB }}" >> src/.env

      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Pull Docker Image
        run: docker pull bukanasa/php-apache:latest

      - name: Delete old Docker container and down Docker Compose
        run: |
          docker compose down --remove-orphans || true
          docker rm -f php-apache || true

      - name: Run Docker Compose
        run: docker compose up -d
