name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Create .env file
        run: |
          cat <<EOF > src/.env
          APP_HOST=${{ secrets.APP_HOST }}
          APP_PORT=${{ secrets.APP_PORT }}
          SENDER_EMAIL_ADDRESS=${{ secrets.SENDER_EMAIL_ADDRESS }}
          SENDER_EMAIL_PASSWORD=${{ secrets.SENDER_EMAIL_PASSWORD }}
          MYSQL_HOST=${{ secrets.MYSQL_HOST }}
          MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
          MYSQL_USER=${{ secrets.MYSQL_USER }}
          MYSQL_PORT=${{ secrets.MYSQL_PORT }}
          MYSQL_DB=${{ secrets.MYSQL_DB }}
          EOF

      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Pull Docker Image
        run: docker pull bukanasa/php-apache:latest

      - name: Stop and remove old Docker containers
        run: |
          docker compose down --remove-orphans || true
          docker rm -f php-apache || true

      - name: Run Docker Compose
        run: docker compose up -d --build
