name: CI Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          cat <<EOF > src/.env
          APP_HOST=${{ secrets.APP_HOST }}
          APP_PORT=${{ secrets.APP_PORT }}
          SENDER_EMAIL_ADDRESS=${{ secrets.SENDER_EMAIL_ADDRESS }}
          SENDER_EMAIL_PASSWORD=${{ secrets.SENDER_EMAIL_PASSWORD }}
          MYSQL_HOST=${{ secrets.MYSQL_HOST }}
          MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
          MYSQL_USER=${{ secrets.MYSQL_USER }}
          MYSQL_PORT=${{ secrets.MYSQL_PORT }}
          MYSQL_DB=${{ secrets.MYSQL_DB }}
          EOF

      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build the Docker image
        run: docker build -f docker/dockerfile -t bukanasa/php-apache:latest .

      - name: Push Docker image to DockerHub
        run: docker push bukanasa/php-apache:latest
